name: Python application

on:
  push:
    paths:
    - 'python/*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10.16
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.16
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Build & Push Image
      run: |
        cd ./python
        docker login --username=sisam22 --password=${{ secrets.DOCKERPW }}
        docker image build -t sisam22/gitops:hellov1.0 .
        docker push sisam22/gitops:hellov1.0
